stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: web:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.ulaidao.com:35000
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 100
