stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: web:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:34527
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
